module.exports = {
  env: {
    es6: true,
    browser: true,
    node: true,
    jest: true,
  },
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:@typescript-eslint/recommended-requiring-type-checking',
    'plugin:import/recommended',
    'plugin:import/typescript',
    'plugin:prettier/recommended',
  ],
  plugins: ['@typescript-eslint'],
  rules: {
    '@typescript-eslint/consistent-type-imports': 'error',
    '@typescript-eslint/indent': 'off',
    '@typescript-eslint/no-explicit-any': 'warn',
    '@typescript-eslint/no-non-null-assertion': 'off',
    '@typescript-eslint/no-misused-promises': 'warn',
    '@typescript-eslint/no-use-before-define': 'off',
    '@typescript-eslint/restrict-template-expressions': 'off',
    'arrow-body-style': 'error',
    'arrow-spacing': ['warn', { before: true, after: true }],
    'comma-dangle': 'off',
    'comma-spacing': 'error',
    'comma-style': 'error',
    curly: ['error', 'multi-line', 'consistent'],
    'dot-location': ['error', 'property'],
    eqeqeq: 'error',
    'global-require': 'off',
    'handle-callback-err': 'off',
    indent: 'off',
    'import/exports-last': 'off',
    'import/first': 'error',
    'import/newline-after-import': 'error',
    'import/no-cycle': 'error',
    'import/extensions': 'off',
    'import/no-extraneous-dependencies': [
      'error',
      { devDependencies: true, peerDependencies: false },
    ],
    'import/order': [
      'warn',
      {
        groups: [
          'builtin',
          'external',
          'internal',
          'parent',
          'sibling',
          'index',
          'object',
          'type',
          'unknown',
        ],
        'newlines-between': 'always',
        alphabetize: {
          order: 'asc',
          caseInsensitive: true,
        },
      },
    ],
    'import/prefer-default-export': 'off',
    // TODO: dig into unresolved import issue
    'import/no-unresolved': 'off',
    'keyword-spacing': 'error',
    'max-nested-callbacks': ['error', { max: 3 }],
    'max-statements-per-line': ['error', { max: 2 }],
    'max-params': ['error', { max: 4 }],
    'no-console': 'warn',
    'no-empty-function': 'error',
    'no-floating-decimal': 'error',
    'no-inline-comments': 'off',
    'no-lonely-if': 'error',
    'no-multi-spaces': 'error',
    'no-multiple-empty-lines': ['error', { max: 2, maxEOF: 1, maxBOF: 0 }],
    'no-nested-ternary': 'error',
    'no-shadow': ['error', { allow: ['err', 'resolve', 'reject'] }],
    'no-trailing-spaces': 'error',
    'no-var': 'error',
    'no-void': 'warn',
    'no-duplicate-imports': 'error',
    'object-curly-newline': 'off',
    'object-curly-spacing': ['error', 'always'],
    'prefer-const': 'warn',
    'prefer-destructuring': 'warn',
    'prefer-spread': 'warn',
    'prefer-template': 'error',
    quotes: ['error', 'single'],
    semi: ['error', 'always'],
    'space-before-blocks': 'error',
    'space-before-function-paren': [
      'error',
      {
        anonymous: 'never',
        named: 'never',
        asyncArrow: 'always',
      },
    ],
    'space-in-parens': 'error',
    'space-infix-ops': 'error',
    'space-unary-ops': 'error',
    'spaced-comment': 'error',
    'vars-on-top': 'error',
    yoda: 'error',
  },
  settings: {
    'import/parsers': {
      '@typescript-eslint/parser': ['.ts', '.tsx'],
    },
    typescript: {
      alwaysTryTypes: true,
      project: ['packages/*/tsconfig.json', 'apps/*/tsconfig.json'],
    },
    'import/resolver': {
      alias: {
        map: [
          ['~/', './src'],
          ['~/components', './src/components'],
          ['~/schemas', './src/schemas'],
          ['~/utils', './src/utils'],
        ],
        extensions: ['.ts', '.js', '.jsx', '.json'],
      },
    },
  },
  reportUnusedDisableDirectives: true,
};
